[build-system]
requires = ["setuptools", "wheel", "oldest-supported-numpy", "packaging>20.9"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--mpl --cov=shap"
testpaths = ["tests"]

[tool.ruff]
# Aim to get all pyflakes logical errors ("F") passing
select = ["F"]
# For now, deselect rules that do not pass
ignore = [
  "F401", # unused imports
  "F811", # Redefinition of unused variable
  "F821", # Undefined name
  "F841", # Local variables assigned but unused
]
