[build-system]
requires = ["setuptools", "wheel", "oldest-supported-numpy", "packaging>20.9"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--mpl"
testpaths = ["tests"]

[tool.ruff]
# Aim to get all pyflakes logical errors ("F") passing
select = ["F"]
# For now, deselect rules that do not pass
ignore = [
  "F811", # Redefinition of unused variable
]

[tool.ruff.per-file-ignores]
# Unused imports often intentional in top-level __init__.py 
"__init__.py" = ["F401"]
