[build-system]
requires = ["setuptools", "wheel", "oldest-supported-numpy", "packaging"]
build-backend = "setuptools.build_meta"

[tool.ruff]
# Aim to get all pyflakes logical errors ("F") passing
# For now, only select a small subset of rules that pass
select = ["F402", "F403", "F404", "F901"]
