name: tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run_tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[test,plots]'
          pip install tensorflow
      - name: Test with pytest
        run: |
          python -m pytest -n auto \
          --cov-report=xml --cov-report=term-missing \
          --durations=20 --junitxml=junit/pytest.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/junit/*.xml'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
