name: tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run_tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install packaging
          python setup.py develop
          pip install '.[test,plots]'
          pip install tensorflow xgboost codecov torch torchvision pylint sentencepiece
      - name: Test with pytest
        run: |
          python -m pytest tests
      - name: Run CodeCov
        run: |
          codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
